name: kuromoji
description: Tokenize Japanese text using dictionaries defined by the Atilika project.
version: 1.0.5
repository: https://github.com/Lexedia/kuromoji

environment:
  sdk: ^3.0.0

dependencies:
  archive: ^4.0.7
  http: ^1.4.0
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.26.2
  lints: ^5.0.0
